In [510]:
import pandas as pd
import DataGathering.FileHandling as files
import jellyfish

In [511]:
gamesOnly = pd.read_csv("GamesOnly.csv")
playerStatsPerGame = pd.read_csv("PlayerStatsPerGame.csv")

In [512]:
teamNames = files.readFileToList("Data/teamNames.txt")
playerNames = files.readFileToList("Data/playerNames.txt")

In [513]:
gamesOnly.head()

Unnamed: 0        Date  GameID     Season M/F                     Team1  \
0           0  2020/12/20  1045.0  2020/2021   M  United Volleys Frankfurt   
1           1  2020/11/04  1001.0  2020/2021   M    Volleyball Bisons Bühl   
2           2  2021/01/23  1065.0  2020/2021   M       VfB Friedrichshafen   
3           3  2020/10/03  2002.0  2020/2021   F          NawaRo Straubing   
4           4  2020/10/29  2019.0  2020/2021   F     Rote Raben Vilsbiburg   

                    Team2  Score1  Score2       Player1Team1  ...  \
0  Volleyball Bisons Bühl       3       1     Imhoff Facundo  ...   
1        TSV Unterhaching       3       0       Thiel Stefan  ...   
2        TSV Unterhaching       3       0     Worsley Joseph  ...   
3     Schwarz-Weiß Erfurt       3       1  Provaroni Claudia  ...   
4        NawaRo Straubing       3       0      Dammer Simona  ...   

        Player7Team2          Player8Team2    Player9Team2     Player10Team2  \
0       Henning Paul     Jurkovics Mathäus      Meier Leon  Ringseis Florian   
1     Brandt Severin         Brandt Niklas   Petrusic Juro     Thom Benjamin   
2     Brandt Severin         Brandt Niklas   Petrusic Juro     Thom Benjamin   
3         Lenz Sindy  Michel Tosi Victoria   Gross Jasmine    Barthel Meghan   
4  Schweigmann Janna           Hänle Marie  Dreblow Sophie     Scholten Iris   

       Player11Team2  Player12Team2  Player13Team2   Player14Team2  \
0  Kronthaler Niklas    Lopez Tomas              -               -   
1     Gehringer Paul  Friedrich Roy  Paduretu Eric  Chefai Mohamed   
2     Gehringer Paul  Friedrich Roy  Paduretu Eric  Chefai Mohamed   
3         Maase Rica   Cole Madelyn              -               -   
4    Gryka Magdalena              -              -               -   

  Player14Team1       Player1Team2  
0             -        Szabó Alpár  
1             -        Suck Fabian  
2             -        Suck Fabian  
3             -    Palmer Madeline  
4             -  Provaroni Claudia  

[5 rows x 38 columns]

In [514]:
playerStatsPerGame[playerStatsPerGame["PlayerName"] == "Grankin Sergey"]

Unnamed: 0      PlayerName M/F                PlayerTeam  \
127          127  Grankin Sergey   M  BERLIN RECYCLING Volleys   
637          637  Grankin Sergey   M  BERLIN RECYCLING Volleys   
722          722  Grankin Sergey   M  BERLIN RECYCLING Volleys   
1073        1073  Grankin Sergey   M  BERLIN RECYCLING Volleys   
1161        1161  Grankin Sergey   M  BERLIN RECYCLING Volleys   
1372        1372  Grankin Sergey   M  BERLIN RECYCLING Volleys   
1460        1460  Grankin Sergey   M  BERLIN RECYCLING Volleys   
2238        2238  Grankin Sergey   M  BERLIN RECYCLING Volleys   
2276        2276  Grankin Sergey   M  BERLIN RECYCLING Volleys   
2475        2475  Grankin Sergey   M  BERLIN RECYCLING Volleys   
2635        2635  Grankin Sergey   M  BERLIN RECYCLING Volleys   
2847        2847  Grankin Sergey   M  BERLIN RECYCLING Volleys   
3177        3177  Grankin Sergey   M  BERLIN RECYCLING Volleys   
3284        3284  Grankin Sergey   M  BERLIN RECYCLING Volleys   
3885        3885  Grankin Sergey   M  BERLIN RECYCLING Volleys   
4260        4260  Grankin Sergey   M  BERLIN RECYCLING Volleys   
5151        5151  Grankin Sergey   M  BERLIN RECYCLING Volleys   
5176        5176  Grankin Sergey   M  BERLIN RECYCLING Volleys   
5306        5306  Grankin Sergey   M  BERLIN RECYCLING Volleys   
5499        5499  Grankin Sergey   M  BERLIN RECYCLING Volleys   
5806        5806  Grankin Sergey   M  BERLIN RECYCLING Volleys   
5890        5890  Grankin Sergey   M  BERLIN RECYCLING Volleys   
6106        6106  Grankin Sergey   M  BERLIN RECYCLING Volleys   
6155        6155  Grankin Sergey   M  BERLIN RECYCLING Volleys   
6204        6204  Grankin Sergey   M  BERLIN RECYCLING Volleys   
6602        6602  Grankin Sergey   M  BERLIN RECYCLING Volleys   
6661        6661  Grankin Sergey   M  BERLIN RECYCLING Volleys   
6756        6756  Grankin Sergey   M  BERLIN RECYCLING Volleys   
7330        7330  Grankin Sergey   M  BERLIN RECYCLING Volleys   
7530        7530  Grankin Sergey   M  BERLIN RECYCLING Volleys   
7718        7718  Grankin Sergey   M  BERLIN RECYCLING Volleys   
8276        8276  Grankin Sergey   M  BERLIN RECYCLING Volleys   
8887        8887  Grankin Sergey   M  BERLIN RECYCLING Volleys   

                  OpposingTeam  Score1  Score2        Date  GameID  \
127           TSV Unterhaching       3       0  2019/10/27  1021.0   
637     Helios GRIZZLYS Giesen       3       2  2019/10/23  1018.0   
722     SWD powervolleys DÜREN       3       0  2019/11/16  1039.0   
1073    Volleyball Bisons Bühl       1       3  2020/10/31  1011.0   
1161    WWK Volleys Herrsching       3       0  2019/10/30  1109.0   
1372       VfB Friedrichshafen       0       3  2020/11/21  1022.0   
1460                VCO Berlin       3       0  2020/11/04  1207.0   
2238    WWK Volleys Herrsching       3       0  2019/11/09  1028.0   
2276  United Volleys Frankfurt       3       2  2019/22/12  1063.0   
2475  United Volleys Frankfurt       2       3  2021/02/06  1074.0   
2635    Volleyball Bisons Bühl       3       0  2021/01/31  1056.0   
2847    WWK Volleys Herrsching       3       0  2020/05/02  1094.0   
3177          TSV Unterhaching       3       0  2021/01/13  1055.0   
3284  Netzhoppers KW-Bestensee       3       1  2021/02/20  1084.0   
3885    Helios GRIZZLYS Giesen       3       2  2021/01/23  1064.0   
4260              SVG Lüneburg       3       0  2019/11/13  1033.0   
5151    SWD powervolleys DÜREN       3       2  2020/25/02  1105.0   
5176                VCO Berlin       3       0  2021/01/16  1216.0   
5306    Volleyball Bisons Bühl       3       0  2019/11/30  1051.0   
5499          TSV Unterhaching       3       0  2020/10/25  1010.0   
5806    Helios GRIZZLYS Giesen       3       1  2020/23/01  1084.0   
5890       VfB Friedrichshafen       3       2  2019/14/12  1059.0   
6106    WWK Volleys Herrsching       3       0  2019/11/24  1043.0   
6155              SVG Lüneburg       3       0  2020/02/08  1099.0   
6204  Netzh

In [515]:
playersStatsPerSet = pd.DataFrame([], columns=["PlayerName", "M/F", "PlayerTeam", "PointsTotal", "PointsDelta", "ServeTotal", "ServeError", "ServePoints", "ReceptionTotal", "ReceptionError", "AttackTotal", "AttackError", "AttackBlocked", "AttackPoints", "BlockPoints"])

In [516]:
values = ["PointsTotal", "PointsDelta", "ServeTotal", "ServeError", "ServePoints", "ReceptionTotal", "ReceptionError", "AttackTotal", "AttackError", "AttackBlocked", "AttackPoints", "BlockPoints"]

In [517]:
for playerName in playerNames:
    d = {}
    d["PlayerName"] = playerName
    allStatsOfPlayer = playerStatsPerGame[playerStatsPerGame["PlayerName"] == playerName]
    if allStatsOfPlayer.size == 0:
        continue
    mf = allStatsOfPlayer.iloc[0]["M/F"]
    d["M/F"] = mf
    thisSeasonStats = allStatsOfPlayer[allStatsOfPlayer["Season"] == "2020/2021"]
    if thisSeasonStats.size == 0:
        continue
    team = thisSeasonStats.iloc[0]["PlayerTeam"].replace('"', '')
    d["PlayerTeam"] = team
    playerTeamScoreSum = allStatsOfPlayer["Score1"].sum()
    opposingTeamsScoreSum = allStatsOfPlayer["Score2"].sum()
    for value in values:
        s = allStatsOfPlayer[value].sum()
        d[value] = s / (playerTeamScoreSum+opposingTeamsScoreSum)
    playersStatsPerSet = playersStatsPerSet.append(d, ignore_index=True)

In [518]:
playersStatsPerSet.to_excel("PlayerPerformances.xlsx")

In [519]:
def lastMatchResult(team1, team2, date):
    matchesOfTeams = gamesOnly[((gamesOnly["Team1"] == team1) & (gamesOnly["Team2"] == team2)) | ((gamesOnly["Team1"] == team2) & (gamesOnly["Team2"] == team1)) & (gamesOnly["Date"] != date)]
    matchesOfTeams = matchesOfTeams.sort_values(by="Date", ascending=False)
    lastResult = matchesOfTeams.iloc[0]
    isReversed = False
    if lastResult["Team1"] == team2:
        isReversed = True
    lastResult = lastResult["Score1"] / (lastResult["Score1"] + lastResult["Score2"])
    if isReversed:
        lastResult = 1 - lastResult
    return lastResult

# Learning

In [520]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import Normalizer

In [521]:
def unison_shuffled_copies(a, b):
    assert len(a) == len(b)
    p = np.random.permutation(len(a))
    return a[p], b[p]

In [522]:
winOrLose = lambda val: 1 if val > 0.5 else 0

In [523]:
Y = gamesOnly["Score1"].to_numpy() / (gamesOnly["Score1"].to_numpy() + gamesOnly["Score2"].to_numpy())

In [524]:
Y

array([0.75, 1.  , 1.  , 0.75, 1.  , 1.  , 0.25, 1.  , 0.75, 0.75, 0.25,
       0.  , 0.25, 1.  , 0.4 , 1.  , 0.4 , 0.75, 0.75, 1.  , 0.4 , 1.  ,
       0.4 , 0.75, 0.6 , 0.4 , 0.25, 0.25, 1.  , 1.  , 0.75, 1.  , 1.  ,
       0.  , 0.  , 0.25, 0.4 , 1.  , 0.75, 0.6 , 0.4 , 0.25, 0.  , 0.75,
       1.  , 0.4 , 0.6 , 1.  , 1.  , 1.  , 0.25, 1.  , 1.  , 0.75, 0.25,
       1.  , 1.  , 1.  , 0.25, 1.  , 0.25, 0.  , 1.  , 1.  , 1.  , 0.75,
       0.6 , 0.25, 0.25, 1.  , 0.6 , 1.  , 1.  , 0.25, 0.25, 0.  , 1.  ,
       0.4 , 0.25, 0.4 , 1.  , 0.25, 0.  , 0.25, 1.  , 0.75, 1.  , 0.6 ,
       0.4 , 1.  , 0.  , 0.  , 0.  , 0.6 , 0.25, 0.4 , 0.75, 0.  , 0.6 ,
       1.  , 0.75, 0.6 , 1.  , 0.6 , 0.25, 0.6 , 0.6 , 0.75, 1.  , 0.25,
       1.  , 0.4 , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.25, 0.25,
       0.  , 0.75, 1.  , 1.  , 0.75, 0.6 , 0.75, 1.  , 0.4 , 1.  , 1.  ,
       1.  , 1.  , 1.  , 0.25, 0.25, 0.4 , 1.  , 0.  , 0.75, 1.  , 0.  ,
       1.  , 0.6 , 0.75, 0.  , 0.  , 0.25, 1.  , 1.

In [525]:
gamesOnly

Unnamed: 0        Date  GameID     Season M/F                     Team1  \
0             0  2020/12/20  1045.0  2020/2021   M  United Volleys Frankfurt   
1             1  2020/11/04  1001.0  2020/2021   M    Volleyball Bisons Bühl   
2             2  2021/01/23  1065.0  2020/2021   M       VfB Friedrichshafen   
3             3  2020/10/03  2002.0  2020/2021   F          NawaRo Straubing   
4             4  2020/10/29  2019.0  2020/2021   F     Rote Raben Vilsbiburg   
..          ...         ...     ...        ...  ..                       ...   
368         368  2020/11/14  2035.0  2020/2021   F     Allianz MTV Stuttgart   
369         369  2020/12/05  2052.0  2020/2021   F     Allianz MTV Stuttgart   
370         370  2019/11/30  1052.0  2019/2020   M    WWK Volleys Herrsching   
371         371  2019/10/23  2018.0  2019/2020   F          NawaRo Straubing   
372         372  2020/02/26  2114.0  2019/2020   F                SC Potsdam   

                      Team2  Score1  Score2         Player1Team1  ...  \
0    Volleyball Bisons Bühl       3       1       Imhoff Facundo  ...   
1          TSV Unterhaching       3       0         Thiel Stefan  ...   
2          TSV Unterhaching       3       0       Worsley Joseph  ...   
3       Schwarz-Weiß Erfurt       3       1    Provaroni Claudia  ...   
4          NawaRo Straubing       3       0        Dammer Simona  ...   
..                      ...     ...     ...                  ...  ...   
368        NawaRo Straubing       3       0        Koskelo Roosa  ...   
369     Schwarz-Weiß Erfurt       3       1        Koskelo Roosa  ...   
370     VfB Friedrichshafen       3       2           Ilic Dorde  ...   
371   Allianz MTV Stuttgart       0       3  Steen Knudsen Ragni  ...   
372     Schwarz-Weiß Erfurt       3       0      Wilczek Natalie  ...   

             Player7Team2          Player8Team2     Player9Team2  \
0            Henning Paul     Jurkovics Mathäus       Meier Leon   
1          Brandt Severin         Brandt Niklas    Petrusic Juro   
2          Brandt Severin         Brandt Niklas    Petrusic Juro   
3              Lenz Sindy  Michel Tosi Victoria    Gross Jasmine   
4       Schweigmann Janna           Hänle Marie   Dreblow Sophie   
..                    ...                   ...              ...   
368        Dreblow Sophie         Scholten Iris                -   
369  Michel Tosi Victoria         Gross Jasmine   Barthel Meghan   
370         Janouch Jakub        Juhkami Martti  Malescha Daniel   
371       Rosenthal Jenna     Jegdic Aleksandra         No Match   
372            Röling Jan            Lenz Sindy   Stauß Mia Anna   

          Player10Team2      Player11Team2    Player12Team2  Player13Team2  \
0      Ringseis Florian  Kronthaler Niklas      Lopez Tomas              -   
1         Thom Benjamin     Gehringer Paul    Friedrich Roy  Paduretu Eric   
2         Thom Benjamin     Gehringer Paul    Friedrich Roy  Paduretu Eric   
3        Barthel Meghan         Maase Rica     Cole Madelyn              -   
4         Scholten Iris    Gryka Magdalena                -              -   
..                  ...                ...              ...            ...   
368                   -                  -                -              -   
369          Maase Rica       Merte Franca     Cole Madelyn              -   
370   Steuerwald Markus    Gjorgiev Nikola  Schmidt Brendan              -   
371      Rivers Krystal   Janiska Jennifer      Berger Lara       No Match   
372  Brisebois Danielle         Maase Rica  Pettke Jennifer  Flory Lindsay   

      Player14Team2 Player14Team1       Player1Team2  
0                 -             -        Szabó Alpár  
1    Chefai Mohamed             -        Suck Fabian  
2    Chefai Mohamed             -        Suck Fabian  
3                 -             -    Palmer Madeline  
4                 -             -  Provaroni Claudia  
..              ...           ...                ...  
368               -         

In [526]:
X = []
for i in range(0, gamesOnly.shape[0]):
    game = gamesOnly.iloc[i]
    dataPoint = np.zeros((1,24+1))
    
    lastResult = lastMatchResult(game["Team1"], game["Team2"], game["Date"])
    dataPoint[0] = lastResult
    
    #print(dataPoint)
    for teamNumber in range(1,3):
        teamStrength = np.zeros((1,12))
        playerCounter = 0
        for playerNumber in range(1,15):
            playerNTeamMName = game["Player{}Team{}".format(playerNumber, teamNumber)]
            if playerNTeamMName == "-":
                continue
            playerStrength = playersStatsPerSet[playersStatsPerSet["PlayerName"] == playerNTeamMName].drop(["PlayerName", "M/F", "PlayerTeam"], axis=1)
            playerStrength = playerStrength.to_numpy()
            if np.size(playerStrength, 0) == 0:
                continue
            playerCounter += 1
            teamStrength += playerStrength
        dataPoint[0,1+(teamNumber-1)*12:1+(teamNumber-1)*12+12] = teamStrength / playerCounter
    X.append(dataPoint.flatten())

In [527]:
X

[array([0.75      , 1.36811272, 0.66723398, 1.9999434 , 0.22834068,
        0.09078429, 1.88321261, 0.11221196, 2.2469675 , 0.15414644,
        0.20222629, 1.09428946, 0.189196  , 1.19638863, 0.56524111,
        1.76903109, 0.21647051, 0.0730244 , 1.41153456, 0.05989442,
        2.02129324, 0.19824159, 0.15654101, 0.91743743, 0.2059268 ]),
 array([0.75      , 1.25915275, 0.55599677, 1.80355691, 0.26497284,
        0.09454757, 1.56310971, 0.07320846, 2.21788267, 0.20634359,
        0.1737826 , 0.99427896, 0.17140847, 0.85918392, 0.07814731,
        1.33010578, 0.30139757, 0.05174253, 1.49247442, 0.10096915,
        1.8970395 , 0.15929367, 0.21937621, 0.72124786, 0.08619353]),
 array([1.        , 1.31582712, 0.690276  , 1.57845281, 0.32573824,
        0.08054935, 1.37135557, 0.08665999, 1.88461044, 0.11708284,
        0.110853  , 1.03618478, 0.19435372, 0.85918392, 0.07814731,
        1.33010578, 0.30139757, 0.05174253, 1.49247442, 0.10096915,
        1.8970395 , 0.15929367, 0.21937621, 

In [528]:
Y = Y.astype(float)
X = np.array(X)

In [529]:
#normer = Normalizer()
#normer.fit(X)
#X = normer.transform(X)

In [530]:
X

array([[0.75      , 1.36811272, 0.66723398, ..., 0.15654101, 0.91743743,
        0.2059268 ],
       [0.75      , 1.25915275, 0.55599677, ..., 0.21937621, 0.72124786,
        0.08619353],
       [1.        , 1.31582712, 0.690276  , ..., 0.21937621, 0.72124786,
        0.08619353],
       ...,
       [0.25      , 1.54872467, 0.58197191, ..., 0.16682532, 1.02503828,
        0.18326733],
       [1.        , 1.75446122, 0.61273912, ..., 0.15155946, 1.02540326,
        0.19083038],
       [0.75      , 1.60750617, 0.79323187, ..., 0.17188746, 0.83165178,
        0.12992897]])

In [531]:
X, Y = unison_shuffled_copies(X, Y)

In [532]:
ind = int(X.shape[0] * 0.95)

In [533]:
X_train = X[:ind]
Y_train = Y[:ind]
X_test = X[ind:]
Y_test = Y[ind:]

In [534]:
if X_test.size == 0:
    X_test = X
    Y_test = Y

In [625]:
lin_reg = LinearRegression()
#log_reg = LogisticRegression()
#rndF_clf = RandomForestClassifier(n_estimators=500, max_depth=2)
rndF_reg = RandomForestRegressor(n_estimators=500, max_depth=2)

model = rndF_reg
model.fit(X_train, Y_train) 

RandomForestRegressor(max_depth=2, n_estimators=500)

In [626]:
def predict(nameTeam1, nameTeam2, date):
    lastResult = lastMatchResult(nameTeam1, nameTeam2, date)
    print(lastResult)
    playersTeam1 = playersStatsPerSet.loc[playersStatsPerSet["PlayerTeam"] == nameTeam1]
    playersTeam2 = playersStatsPerSet.loc[playersStatsPerSet["PlayerTeam"] == nameTeam2]
    teamStrength1 = playersTeam1.drop(["PlayerName" ,"M/F", "PlayerTeam"], axis = 1).sum(axis=0).to_numpy() / playersTeam1.shape[1]
    teamStrength2 = playersTeam2.drop(["PlayerName" ,"M/F", "PlayerTeam"], axis = 1).sum(axis=0).to_numpy() / playersTeam2.shape[1]
    X = np.concatenate((np.array([lastResult]), teamStrength1, teamStrength2))
    #X = normer.transform([X])
    return model.predict([X])

In [627]:
pred = model.predict(X_test)

In [628]:
pred

array([0.8202635 , 0.27694103, 0.70755055, 0.71277394, 0.66152378,
       0.61847732, 0.70779092, 0.50180042, 0.36978151, 0.45346198,
       0.80917005, 0.26862317, 0.27498694, 0.62670409, 0.73060569,
       0.39627083, 0.54288096, 0.78929359, 0.70132269])

In [629]:
pred = np.array([winOrLose(p) for p in pred])
real = np.array([winOrLose(p) for p in Y_test])

In [630]:
rmse = np.sqrt(np.sum(np.square(real - pred)) / real.shape[0])
print(rmse)

0.5619514869490163


In [631]:
corr = np.sum(pred == real)
print(corr)

13


In [632]:
fal = real.shape[0] - corr
print(fal)

6


In [633]:
real.shape[0]

19

In [634]:
model.coef_

AttributeError: 'RandomForestRegressor' object has no attribute 'coef_'

# Predictor

In [635]:
team1 = "VfB Friedrichshafen"
team2 = "Helios GRIZZLYS Giesen"
date = "2021/02/24"

In [636]:
gamesOnly[(gamesOnly["Team1"] == team2) & (gamesOnly["Team2"] == team1) | (gamesOnly["Team1"] == team1) & (gamesOnly["Team2"] == team2)]

Unnamed: 0        Date  GameID     Season M/F                   Team1  \
14           14  2019/11/18  1042.0  2019/2020   M  Helios GRIZZLYS Giesen   
48           48  2019/13/11  1035.0  2019/2020   M     VfB Friedrichshafen   
214         214  2020/11/28  1028.0  2020/2021   M  Helios GRIZZLYS Giesen   
338         338  2020/22/02  1108.0  2020/2021   M     VfB Friedrichshafen   

                      Team2  Score1  Score2      Player1Team1  ...  \
14      VfB Friedrichshafen       2       3  Ringseis Florian  ...   
48   Helios GRIZZLYS Giesen       3       0    Worsley Joseph  ...   
214     VfB Friedrichshafen       0       3   Eshenko Pearson  ...   
338  Helios GRIZZLYS Giesen       3       1    Worsley Joseph  ...   

          Player7Team2          Player8Team2            Player9Team2  \
14       Janouch Jakub        Juhkami Martti         Malescha Daniel   
48    Schippmann Timon              No Match            Kvrzic Milan   
214  van de Velde Arno          Vincic Dejan         Bonin Ben-Simon   
338      Stalekar Saso  Siirilä Tommi Juhani  Francös Pedro Henrique   

                 Player10Team2             Player11Team2      Player12Team2  \
14           Steuerwald Markus           Gjorgiev Nikola    Schmidt Brendan   
48                Busch Amelie             Kapur Milorad                  -   
214               Böhme Marcus               Weber Linus        Maase Lukas   
338  Clere Jerome Claude Pierr  Duarte Souza Da Silva Do  Kronthaler Niklas   

            Player13Team2     Player14Team2 Player14Team1      Player1Team2  
14                      -                 -             -    Worsley Joseph  
48                      -                 -             -      Wagner Hauke  
214  Fiel Rodriguez David  Marechal Nicolas             -    Worsley Joseph  
338       Malescha Daniel                 -             -  Ringseis Florian  

[4 rows x 38 columns]

In [637]:
predict(team1, team2, date)

0.75


array([0.7201732])

In [638]:
predict(team2, team1, date)

0.25


array([0.45946197])

In [639]:
prediction = (predict(team1, team2, date) + (1-predict(team2, team1, date))) / 2
print("My Prediction", prediction)

0.75
0.25
My Prediction [0.63035562]


In [640]:
"VfB Friedrichshafen"
"SWD powervolleys DÜREN"
"BERLIN RECYCLING Volleys"
"WWK Volleys Herrsching"
"United Volleys Frankfurt"
"SVG Lüneburg"
"Netzhoppers KW-Bestensee"
"Helios GRIZZLYS Giesen"
"Volleyball Bisons Bühl"
"VCO Berlin"
"TSV Unterhaching"
"Dresdner SC"
"Allianz MTV Stuttgart"
"SSC Palmberg Schwerin"
"Rote Raben Vilsbiburg"
"SC Potsdam"
"VfB Suhl LOTTO Thüringen"
"NawaRo Straubing"
"VC Wiesbaden"
"USC Münster"
"Ladies in Black Aachen"
"Schwarz-Weiß Erfurt"

'Schwarz-Weiß Erfurt'